# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.__config__.show())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
ar = np.array([1,2,3,4,5])
print(ar.size)
print(ar.itemsize)

5
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: ignored

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
vec = np.zeros(10)
vec[4] = 1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
a=np.arange(10,50)
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
z = np.array([1,2,0,0,4,0])
np.nonzero(z)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
a = np.random.uniform((3,3,3))
a

array([1.34523649, 2.30306003, 1.36511121])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
ar = np.random.random((10,10))
print(ar.min(), ar.max())

0.005275209751819165 0.9981443200886809


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
rv = np.random.random(30)
print(rv.mean())

0.5186445257586836


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
ar = np.ones((10,10))
ar[1:-1,1:-1] = 0
ar

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
ar = np.random.random((3,3))
np.pad(ar,1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.24320923, 0.7662823 , 0.55840023, 0.        ],
       [0.        , 0.6401899 , 0.91249856, 0.46904996, 0.        ],
       [0.        , 0.77698241, 0.49730163, 0.20218306, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
#nan
#False
#False
#nan
#False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [18]:
z = np.diag(np.arange(1,5), k = -1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [19]:
ar = np.zeros((8,8),dtype=int)
ar[1::2, ::2] = 1
ar[::2, 1::2] = 1
ar

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [20]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [21]:
ar= np.array([[0,1], [1,0]])
z = np.tile(ar,(4,4))
print (z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [22]:
ar = np.random.random((5,5))
ar = (ar-ar.min())/(ar.max()-ar.min())
ar

array([[0.52763007, 0.64601399, 0.65851837, 1.        , 0.42405096],
       [0.37659727, 0.44286572, 0.92539256, 0.        , 0.18976247],
       [0.42442176, 0.41276698, 0.05548632, 0.46489953, 0.04987377],
       [0.90687476, 0.87669547, 0.3172066 , 0.2406528 , 0.68807148],
       [0.31179564, 0.97273351, 0.55369833, 0.24208969, 0.52175273]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [23]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
color


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [24]:
ar1 = np.arange(15).reshape(5,3)
ar2 = np.arange(6).reshape(3,2)
np.dot(ar1,ar2)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [25]:
ar = np.arange(15)
ar[(ar>3) & (ar<=7)] = -1
ar

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
#9
#10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z = np.arange(5)
#[  1,   1,   4,  27, 256]
#[0, 1, 2, 4, 8]
#[False, False, False, False, False]
#[0+0j, 0+1j, 0+2j, 0+3j, 0+4j]
#[0,1,2,3,4]
#ValueError

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
#nan
#0
#[-9.22337204e+18]

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [29]:
z = np.random.uniform(-10,+10,10)
print(z)
# print(np.ceil(np.abs(z)))
print(np.copysign(np.ceil(np.abs(z)), z))

[-7.74674498 -6.27396871  7.62702008 -6.44262159 -7.4318155   1.12440841
  5.39588022  2.78389124 -2.87650889  4.45374687]
[-8. -7.  8. -7. -8.  2.  6.  3. -3.  5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [30]:
a1 = np.arange(5,15)
a2 = np.arange(10,20)
np.intersect1d(a1,a2)

array([10, 11, 12, 13, 14])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [31]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
#False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [33]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)
yesterday,today,tomorrow

(numpy.datetime64('2021-09-29'),
 numpy.datetime64('2021-09-30'),
 numpy.datetime64('2021-10-01'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [34]:
jul2016 = np.arange('2016-07','2016-08',dtype='datetime64[D]')
jul2016

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [35]:
A = np.array([14,2,10],dtype = 'float')
B = np.array([4,5,6],dtype = 'float')
np.add(A,B, out= B)
np.divide(A,2,out = A)
np.negative(A,out = A)
np.multiply(A,B, out=A)

array([-126.,   -7.,  -80.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [36]:
ar = np.random.uniform(-10, +10, 10)
print(ar)
print(np.copysign(np.floor(np.abs(ar)),ar))
print(np.copysign(np.ceil(np.abs(ar))-1,ar))
print(ar.astype(np.int32))
print(np.trunc(ar))

[-0.65521542  3.84560275 -1.16173772  2.97097795  0.58447228 -8.37532417
  8.92775123  8.03142422  9.38592942 -5.63047022]
[-0.  3. -1.  2.  0. -8.  8.  8.  9. -5.]
[-0.  3. -1.  2.  0. -8.  8.  8.  9. -5.]
[ 0  3 -1  2  0 -8  8  8  9 -5]
[-0.  3. -1.  2.  0. -8.  8.  8.  9. -5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [37]:
ar = np.zeros((5,5))
ar = ar + np.arange(5)
ar

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [38]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [41]:
np.linspace(start=0, stop=11, num=10, endpoint=False)

array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [42]:
ar = np.random.random(size=10)
ar.sort()
print(ar)

[0.11277681 0.15553485 0.20919753 0.29550942 0.34767752 0.4608748
 0.62641027 0.68292341 0.83921876 0.96969755]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [44]:
ar = np.array([156,546,56,564,58])
print(np.add.reduce(ar))

1380


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [45]:
a = np.random.random(10)
b = np.random.random(10)
if np.array_equal == True or np.allclose == True:
  print('Both arrays are equal')
else:
  print('Both arrays are not equal')


Both arrays are not equal


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [46]:
x = np.arange(10)
x.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [47]:
ar = np.random.random((10, 2))
x, y = ar[:, 0], ar[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
t = np.arctan2(y, x)
print(r)
print(t)

[1.13135614 0.65239262 1.00807396 0.63444971 1.15476792 1.12205724
 1.14396566 1.18256012 0.99829019 0.98838799]
[0.86529881 0.02176881 0.78991274 1.3754039  0.80963408 1.00949525
 0.83624496 0.56511942 0.95048092 0.12387855]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [48]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.05431984 0.59765703 0.55867597 0.46438323 0.68595265 0.15070295
 0.         0.2265868  0.66278349 0.78135026]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [49]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [50]:
x = np.random.random((3, 3))
y = np.random.random((3, 3))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
# print(c)
np.linalg.det(c)

array([[-11383.0322373 ,   1245.48884282,    -30.62989695],
       [   -41.07400899,  -2689.5288237 ,  -4835.53964413],
       [ 15887.62193659,    -29.88323441,   -147.40682016]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [51]:
#Int
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
  # print(np.finfo(dtype).eps)
#Float
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [52]:
import sys
np.set_printoptions(precision=3,threshold=sys.maxsize)
ar = np.random.random(10)
print(ar)

[0.03  0.689 0.632 0.768 0.331 0.25  0.217 0.893 0.666 0.322]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [53]:
x = np.arange(50)
y = np.random.uniform(0,50)
index = (np.abs(x-y)).argmin()
print(x[index])

16


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [54]:
ar = np.zeros(10,[('position',[('x', float, 1),('y', float, 1)]),('color', [('r', float, 1),('g', float, 1),('b', float, 1)])])
print(ar)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [55]:
ar = np.random.random((100,2))
x,y = np.atleast_2d(ar[:,0], ar[:,1])
dist = np.sqrt( (y-y.T)**2 + (y-y.T)**2)
print(dist)

[[0.000e+00 5.481e-02 1.113e+00 7.093e-01 8.454e-01 5.912e-02 8.632e-01
  4.144e-01 9.930e-01 1.110e+00 1.164e+00 6.576e-02 1.093e+00 5.953e-01
  1.114e+00 1.249e+00 4.580e-01 1.089e+00 3.423e-02 8.897e-01 1.939e-02
  1.072e+00 3.248e-02 1.088e-01 2.969e-01 1.683e-02 1.109e-01 1.072e+00
  1.052e+00 8.027e-01 6.362e-01 5.776e-01 9.095e-01 9.989e-02 1.050e-01
  6.308e-02 4.233e-01 8.923e-01 7.743e-01 4.722e-01 1.158e-03 2.384e-01
  1.757e-01 5.020e-02 1.159e+00 7.410e-01 3.678e-01 1.740e-01 2.825e-01
  3.872e-01 7.009e-01 4.284e-01 6.343e-01 3.733e-01 6.461e-01 7.205e-01
  7.443e-01 1.125e-01 1.077e+00 9.881e-01 4.532e-01 3.053e-01 4.851e-02
  8.400e-01 9.986e-01 6.220e-01 8.598e-01 6.803e-01 1.246e-02 6.854e-01
  5.031e-01 2.128e-01 5.317e-01 9.570e-03 7.168e-01 1.635e-01 4.848e-01
  3.719e-03 4.485e-02 8.821e-01 1.116e+00 1.255e-01 9.691e-02 1.252e+00
  1.193e-01 7.024e-01 1.579e-01 1.900e-01 5.227e-01 5.728e-01 5.946e-02
  1.087e+00 7.191e-01 2.060e-01 1.775e-01 1.138e+00 3.987e-02 1.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [56]:
ar = np.arange(10)
ar = ar.astype(np.int32,copy=False)
print(ar)


[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [57]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n6, , , 7, 8\n, , 9,10,11\n""")
ar = np.genfromtxt(s, delimiter=",")
print(ar)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [58]:
ar = np.arange(9).reshape(3,3)
for i, value in np.ndenumerate(ar):
  print(i, value)
print(" ")
for i in np.ndindex(ar.shape):
  print(i, ar[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [59]:
x, y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
gArr = np.exp(-((d-mu)**2 / ( 2.0 * sigma**2 )))
print(gArr)

[[0.368 0.535 0.607 0.535 0.368]
 [0.535 0.779 0.882 0.779 0.535]
 [0.607 0.882 1.    0.882 0.607]
 [0.535 0.779 0.882 0.779 0.535]
 [0.368 0.535 0.607 0.535 0.368]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [60]:
p = 12
ar = np.ones((4,6))
np.put(ar, np.random.choice(range(4*6), p, replace=False),0)
print(ar)

[[1. 1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [61]:
ar = np.random.rand(3, 4)
newAr = ar - ar.mean(axis=1, keepdims=True)
print(newAr)

[[-0.023 -0.13   0.047  0.106]
 [ 0.195 -0.455  0.036  0.225]
 [-0.289  0.117  0.125  0.047]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [62]:
n = 1
ar = np.random.randint(0,10,(5,5))
print(ar)
sortAr =ar[ar[:,n].argsort()] 
print(sortAr)

[[3 8 9 9 5]
 [2 8 2 9 8]
 [7 1 1 3 5]
 [9 3 4 8 3]
 [0 3 5 3 0]]
[[7 1 1 3 5]
 [9 3 4 8 3]
 [0 3 5 3 0]
 [3 8 9 9 5]
 [2 8 2 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [63]:
ar = np.random.randint(0,3,(3,10))
print((~ar.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [64]:
ar = np.random.uniform(0,1,10)
val = 0.5
ans = ar.flat[np.abs(ar - val).argmin()]
print(ar,ans)

[0.735 0.871 0.242 0.533 0.094 0.493 0.922 0.796 0.816 0.622] 0.492552369566025


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [65]:
ar1 = np.arange(3).reshape(3,1)
ar2 = np.arange(3).reshape(1,3)
iterate = np.nditer([ar1,ar2,None])
print(ar1,ar2)
for x,y,z in iterate: 
  z[...] = x + y
print(iterate.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [66]:
class NamedArray(np.ndarray):
  def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
  def __array_finalize__(self, obj):
    if obj is None:
      return
    self.info = getattr(obj, 'name', "no name")

ar = NamedArray(np.arange(10), "ARRAY")
print (ar.name)

ARRAY


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)